version: '3.7'
services:
  db:
    image: mysql:5.6.48
    container_name: mysql-5.6
    user: 999:999
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
      - TZ=Asia/Shanghai
    networks:
      - mysql_56
    ports:
      - "3306:3306"
    volumes:
      - ./persistence/data:/var/lib/mysql
      - ./persistence/conf:/etc/mysql/conf.d
      - ./persistence/logs:/var/log/mysql

networks:
  mysql_56: