version: "3.7"
services: 
  nexus3:
    image: sonatype/nexus3
    container_name: nexus3
    restart: unless-stopped
    ports: 
    - 8081:8081
    volumes: 
    - ./persistence/nexus-data:/nexus-data
    environment:
    - TZ=Asia/Shanghai
#    - INSTALL4J_ADD_VM_PARAMS