version: '3.7'
services:
  db:
    image: mysql:5.7.30
    container_name: mysql-5.7
    user: 999:999
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
      - TZ=Asia/Shanghai
    networks:
      - default
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./persistence/data:/var/lib/mysql
      - ./persistence/conf:/etc/mysql/conf.d
      - ./persistence/logs:/var/log/mysql

networks:
  default:
    name: mysql_5.7