version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.8.4-management
    container_name: rabbitmq1
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672" 
      - "15672:15672"
    hostname: rabbit1
