version: '3'
services: 
  nginx:
    image: nginx:1.17.1
    container_name: nginx-1.17.1
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    ports: 
      - 80:80
    volumes: 
      - ./persistence/conf:/etc/nginx/conf.d:ro
      - ./persistence/html:/usr/share/nginx/html
      - ./persistence/logs:/tmp/nginx-logs
