version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8080:8080"
      - "50000:50000"
#    network_mode: host
    volumes:
      - ./persistence/jenkins/home:/var/jenkins_home
      - ./persistence/jenkins/tools:/opt/tools
      