version: '3'
services:
  service-name:
    build:
      context: ./dir
      dockerfile: Dockerfile-alternate
      args:
        buildno: 1
      labels:
        - "com.example.description=Accounting webapp"
        - "com.example.department=Finance"
        - "com.example.label-with-empty-value"
      target: prod
    image: ubuntu:16.04
    container_name: services
    user: 999:999
    restart: unless-stopped
    privileged: true
    depends_on:
      - db
      - redis
    environment:
      - TZ=Asia/Shanghai
    working_dir: /usr/local/tomcat
#    network_mode: host
    ports:
      - "3306:3306"
    hostname: rabbit1
    networks:
      - network_name
    volumes:
      - ./persistence/tmp:/tmp
      - volumes_name:/var/log
#    command: --allow-http --password=P@ssw0rd123
    command: redis-server /usr/local/etc/redis/redis.conf

networks:
  network_name:

volumes:
  volumes_name:
