version: "3.7"
services: 
  redis:
    image: redis:5.0.7
    container_name: redis
    restart: unless-stopped
    volumes: 
      - redis-data:/data
    ports: 
      - 6379:6379

volumes: 
  redis-data:
